# Generated by Django 5.1.4 on 2024-12-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_alter_timesheet_clockout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='clockOut',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
